<template>
   <div>
    <SectionsHomeBanner/>
    <SectionsHomeFeatures/>
    <SectionsHomeFastest/>
    <SectionsHomeNewsletters/>
    <SectionsHomePartners/>
    <SectionsHomeTestimonials/>
    <SectionsHomePricing/>
    <SectionsHomeContactUs/>
   </div>
</template>
